$(document).ready(function(){
  $("#get").click(function(){
    $("#two").toggleClass("hid");
	$("#get").toggleClass("hid");
  });
});
$(document).ready(function(){
  $("#two").click(function(){
    $("#two").toggleClass("hid");
	$("#get").toggleClass("hid");
  });
});